wip for team tokens
pulumi/pulumi-pulumiservice pull request #98
Opened 2023-02-22 07:33 UTC by jaxxstorm

2023-02-28 10:03 UTC, pierskarsenbarg requested changes
Are you planning on other examples (maybe do a `convert`)?

2023-02-28 10:03 UTC, pierskarsenbarg commented on provider/pkg/provider/webhook.go
> +
Delete lines

2023-02-28 14:15 UTC, jaxxstorm commented on examples/yaml-webhooks/Pulumi.yaml
> +      organizationName: lbrlabs
yep, will fix!

2023-02-28 14:55 UTC, jaxxstorm commented on provider/pkg/internal/pulumiapi/teamtokens.go
> +	if len(tokenId) == 0 {
Should be implemented now

2023-02-28 14:55 UTC, jaxxstorm commented on provider/pkg/provider/teamaccesstoken.go
> +	//"github.com/pulumi/pulumi-pulumiservice/provider/pkg/internal/serde"
Removed!

2023-02-28 14:56 UTC, jaxxstorm commented on provider/pkg/provider/webhook.go
> +
Removed!

2023-02-28 20:13 UTC, jaxxstorm commented
I cannot for the life of me figure out why that yaml test fails..

2023-02-28 20:42 UTC, djgrove reviewed
Overall lgtm, couple small suggestions

2023-02-28 20:42 UTC, djgrove commented on provider/pkg/provider/orgaccesstoken.go
> +	//"github.com/pulumi/pulumi-pulumiservice/provider/pkg/internal/serde"
```suggestion
```

2023-03-01 17:02 UTC, pierskarsenbarg requested changes
One comment about org names

2023-03-01 17:02 UTC, pierskarsenbarg commented on examples/yaml-team-token/Pulumi.yaml
> +      organizationName: lbrlabs
Don't forget these

2023-03-01 17:23 UTC, pierskarsenbarg approved these changes

2023-03-01 17:23 UTC, merged